config/routes.rb
Rails.application.routes.draw do
  # get 'answers/create'
  # get 'answers/update'
  root to: 'pages#home'

  devise_for :users

  # DASHBOARDS
  resource :dashboard, only: :show
  namespace :admin do
    resource :dashboard, only: :show
  end

  # ACCOUNT VALIDATION FOR INVITED USERS
  resource :validate_accounts, only: [:edit, :update]

  # ACCESS GROUPS
  resource :access_groups, only: [:update]

  # ADMIN ONLY
  resources :recommandations, only: [:edit, :update, :destroy]

  resources :campaigns, only: [:index, :show, :create, :update, :destroy]

  resources :group_campaigns, only: [:create, :destroy]

  resources :axes, only: [:index, :create, :destroy, :update, :show] do
    resources :recommandations, only: [:create]
  end

  resources :admin_users, only: [:index, :create]

  resources :chatrooms, only: [:new, :show] do
    resources :messages, only: [:create]
  end
  # GLOBAL ROUTES

  resources :surveys, only: [:index, :new, :create, :destroy, :edit, :update, :show] do
    resources :questions, only: [:new, :create ]
  end

  resources :questions, only: [ :edit, :update, :destroy ] do
    resources :propositions, only: [:create]
  end

  resources :propositions, only: [ :edit, :update, :destroy ]

  resources :answers, only: [:create, :update]

  resources :groups, only: [:index, :create, :destroy, :update]

  resources :group_campaigns, only: [:show], path: "results", as: 'results'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :user_groups, dependent: :destroy
  has_many :users, through: :user_groups
  has_many :group_campaigns
  has_many :campaigns, through: :group_campaigns

  validates :name, presence: true, length: { minimum: 3 }
  validates :description, presence: true, length: { minimum: 10 }
  validates :start_date, presence: true
  validates :end_date, presence: true

  include StartBeforeEndConcern

  def members
    users.includes(:user_groups).where(user_groups: {role: 'M'} )
  end

  def referent
    users.includes(:user_groups).where(user_groups: {role: 'R'} ).first
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[edit update destroy]

  def index
    @groups = policy_scope(Group).where(user: current_user)
    params[:id] ? set_group : new
    @label = params[:id] ? 'Enregistrer' : 'Créer'
  end

  def new
    @group = Group.new
    authorize @group
  end

  def create
    @group = Group.new(group_params)
    authorize @group
    @group.user = current_user
    if @group.save
      redirect_to groups_path(anchor: "group-#{@group.id}")
    else
      @groups = policy_scope(Group).where(user: current_user)
      render :index
    end
  end

  def update
    @group.update(group_params)
    @group.save ? (redirect_to groups_path(anchor: "group-#{@group.id}")) : (render :new)
  end

  def destroy
    @group.destroy
  end

  private

  def set_group
    @group = Group.find(params[:id])
    authorize @group
  end

  def group_params
    params.require(:group).permit(:name, :start_date, :end_date, :description, :id)
  end

end

app/views/groups/_form.html.erb
<% range_class = label == 'Créer' ? 'range_start' : 'range_start_edit' %>
<%= simple_form_for([group], remote: true) do |f| %>
  <%= f.input :name, label: "Nom du groupe" %>
  <%= f.input :description %>
  <div style='position: relative;'>
    <%= f.input :start_date, label: "Dates du projet", as: :string, required: false, input_html: {id: range_class, class: "d-none"} %>
    <a id='reset-dates' href="#"><i class="fas fa-undo-alt"></i> Clear</a>
  </div>
  <%= f.input :end_date, label: false, as: :string, required: false, input_html: {id: "range_end", class: "d-none"}  %>
  <%= f.submit label, class: 'twi-btn lblue-btn'%>
<% end %>

app/views/groups/_group_card.html.erb
<div class="main-card" id=<%= "group-#{group.id}" %> >

  <div class="info">
    <%= render 'groups/group_card_head', group: group %>
    <p><%= group.description %></p>
  </div>

  <div class="right">
    <div class="actions">
      <% if policy(group).edit? %>
        <%= link_to '<i class="fas fa-pencil-alt"></i>'.html_safe, groups_path(id: group) %>
      <% end %>
      <% if policy(group).destroy? %>
        <%= link_to('<i class="fas fa-trash"></i>'.html_safe, group_path(group), class:'no-scroll-btn',
          method: :delete,
          data: { confirm: "Etes vous sur de vouloir supprimer le groupe #{group.name} ?" },
          remote: true, id: "delete-group-#{group.id}")
        %>
      <% end %>
    </div>
    <div class="right-bottom">
      <p>Du <br>
      <%= l(group.start_date, format: '%d %B %Y', locale: 'fr') %> <br>
      Au <br>
      <%= l(group.end_date, format: '%d %B %Y', locale: 'fr') %></p>
    </div>
  </div>

</div>

app/views/groups/_group_card_head.html.erb
<% ref = group.users.includes(:user_groups).where(user_groups: {role: 'R'}).first %>

<div class="head">
  <h2><%= group.name %></h2>
  <div class="subhead">
    <h3><strong>Référent :</strong> <%= ref ? "#{ref.first_name} #{ref.last_name}" : 'A définir' %></h3>
    <div class="avatars">
      <% group.users.each do |user| %>
        <% if user.photo.attached? %>
          <%= cl_image_tag user.photo.key, alt: "profile pic", class: "avatar" %>
        <% else %>
          <%= image_tag 'profile.svg', alt: "profile pic", class: "avatar" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/destroy.js.erb
// let card = document.getElementById(`group-${<%= @group.id %>}`);
card = document.querySelector(`#group-${<%= @group.id %>} + .main-card`)
card.classList.add('fade-card');

noDisplay = (element) => {
  card.classList.add('no-display');
}

setTimeout(noDisplay, 1000);

app/views/groups/index.html.erb
<div class="main-cards-container">

  <div>
    <% @groups.each do |group| %>
      <div style='position: relative; top: -120px'id=<%= "group-#{group.id}" %>></div>
      <%= render 'group_card', group: group %>
    <% end %>
  </div>

  <div class="twi-form sticky-form">
    <%= render "form", group: @group, label: @label %>
  </div>

</div>