config/routes.rb
Rails.application.routes.draw do
  # get 'answers/create'
  # get 'answers/update'
  root to: 'pages#home'

  devise_for :users

  # DASHBOARDS
  resource :dashboard, only: :show
  namespace :admin do
    resource :dashboard, only: :show
  end

  # ACCOUNT VALIDATION FOR INVITED USERS
  resource :validate_accounts, only: [:edit, :update]

  # ACCESS GROUPS
  resource :access_groups, only: [:update]

  # ADMIN ONLY
  resources :recommandations, only: [:edit, :update, :destroy]

  resources :campaigns, only: [:index, :show, :create, :update, :destroy]

  resources :group_campaigns, only: [:create, :destroy]

  resources :axes, only: [:index, :create, :destroy, :update, :show] do
    resources :recommandations, only: [:create]
  end

  resources :admin_users, only: [:index, :create]

  resources :chatrooms, only: [:new, :show] do
    resources :messages, only: [:create]
  end
  # GLOBAL ROUTES

  resources :surveys, only: [:index, :new, :create, :destroy, :edit, :update, :show] do
    resources :questions, only: [:new, :create ]
  end

  resources :questions, only: [ :edit, :update, :destroy ] do
    resources :propositions, only: [:create]
  end

  resources :propositions, only: [ :edit, :update, :destroy ]

  resources :answers, only: [:create, :update]

  resources :groups, only: [:index, :create, :destroy, :update]

  resources :group_campaigns, only: [:show], path: "results", as: 'results'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <% if alert.class == Array %>
      <%= alert.join('</br>').html_safe %>
    <% else %>
      <%= alert %>
    <% end %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div id="header">
  <%= link_to '<i class="fas fa-home"></i>'.html_safe, root_path, class: "home-logo" %>
  <%= image_tag 'logo.png', class: 'twi-logo' %>
  <h1>TeamWorkInteract</h1>
  <% if current_user %>
  <div class="profile-pic">
    <%= link_to edit_user_registration_path do %>
      <% if current_user.photo.attached? %>
        <%= cl_image_tag current_user.photo.key, alt: "profile pic"%>
      <% else %>
        <%= image_tag 'profile.svg', alt: "profile pic" %>
      <% end %>
    <% end %>
  </div>
  <% end %>
</div>

app/views/shared/_menu-items.html.erb
<ul class="menu">

    <% if current_user %>
      <% if policy(User).index? %>
        <li <% if request.path.match?(/\/admin_users.*/) %> class='activ-item' <% end %>>
          <div class='item-content'>
            <p>Utilisateurs</p>
            <%= link_to 'Utilisateurs', admin_users_path %>
          </div>
        </li>
      <% end %>

      <% if policy(Group).index? %>
        <li <% if request.path.match?(/\/groups.*/) %> class='activ-item' <% end %>>
          <div class='item-content'>
            <p>Groupes</p>
            <%= link_to 'Groupes', groups_path %>
        </li>
      <% end %>

      <% if policy(Campaign).index? %>
        <li <% if request.path.match?(/\/campaigns.*/) %> class='activ-item' <% end %>>
          <div class='item-content'>
            <p>Campagnes</p>
            <%= link_to 'Campagnes', campaigns_path %>
          </div>
         </li>
      <% end %>

      <% if policy(Survey).index? %>
        <li <% if request.path.match?(/\/surveys.*/) %> class='activ-item' <% end %>>
          <div class='item-content'>
            <p>Questionnaires</p>
            <%= link_to 'Questionnaires', surveys_path %>
          </div>
        </li>
      <% end %>

      <% if policy(Axe).index? %>
        <li <% if request.path.match?(/\/axes.*/) %> class='activ-item' <% end %>>
          <div class='item-content'>
            <p>Axes</p>
            <%= link_to 'Axes', axes_path %>
          </div>
        </li>
      <% end %>

      <% if @current_campaign && policy(@current_campaign.survey).show? %>
        <li <% if request.path.match?(/\/surveys.*/)%> class='activ-item' <% end %>>
          <div class='item-content'>
            <p>Questionnaire</p>
            <%= link_to 'Questionnaire', survey_path(@current_campaign.survey) %>
          </div>
        </li>
      <% end %>

      <% if @current_group_campaign && policy(@current_group_campaign).show? %>
        <li <% if request.path.match?(/\/results.*/)%> class='activ-item' <% end %>>
          <div class='item-content'>
            <p>Resultats</p>
            <%= link_to 'Resultats', result_path(@current_group_campaign) %>
          </div>
        </li>
      <% end %>
    <% end %>

  </ul>

app/views/shared/_phone-burger.html.erb
<div class="phone-burger" data-controller="phone-menu">
  <div class="burger" data-phone-menu-target="burger" data-action="click->phone-menu#revealMenu">
    <span></span>
  </div>
</div>

app/views/shared/_phone-menu.html.erb
<div class="phone-menu">
  <%= render 'shared/menu-items' %>
</div>

app/views/shared/_twi-navbar.html.erb
<div class="twi-navbar">
  <%= render 'shared/menu-items' %>

  <% if current_user %>

      <%= link_to 'Deconnexion', destroy_user_session_path, method: :delete, class: 'twi-btn dblue-btn logout-btn' %>

  <% elsif controller_name != 'sessions' %>
    <div class="actions home-actions">
      <% if controller_name = 'registrations' %>
        <%= link_to 'Connexion', new_user_session_path, class: "twi-btn lblue-btn full-width-btn" %>
      <% end %>
      <% if controller_name != 'registrations' %>
        <%= link_to 'Inscription', new_user_registration_path, class: 'twi-btn dblue-btn' %>
      <% end %>
    </div>
  <% end %>
  <%= render 'shared/phone-burger' %>
</div>