config/routes.rb
Rails.application.routes.draw do
  # get 'answers/create'
  # get 'answers/update'
  root to: 'pages#home'

  devise_for :users

  # DASHBOARDS
  resource :dashboard, only: :show
  namespace :admin do
    resource :dashboard, only: :show
  end

  # ACCOUNT VALIDATION FOR INVITED USERS
  resource :validate_accounts, only: [:edit, :update]

  # ACCESS GROUPS
  resource :access_groups, only: [:update]

  # ADMIN ONLY
  resources :recommandations, only: [:edit, :update, :destroy]

  resources :campaigns, only: [:index, :show, :create, :update, :destroy]

  resources :group_campaigns, only: [:create, :destroy]

  resources :axes, only: [:index, :create, :destroy, :update, :show] do
    resources :recommandations, only: [:create]
  end

  resources :admin_users, only: [:index, :create]

  resources :chatrooms, only: [:new, :show] do
    resources :messages, only: [:create]
  end
  # GLOBAL ROUTES

  resources :surveys, only: [:index, :new, :create, :destroy, :edit, :update, :show] do
    resources :questions, only: [:new, :create ]
  end

  resources :questions, only: [ :edit, :update, :destroy ] do
    resources :propositions, only: [:create]
  end

  resources :propositions, only: [ :edit, :update, :destroy ]

  resources :answers, only: [:create, :update]

  resources :groups, only: [:index, :create, :destroy, :update]

  resources :group_campaigns, only: [:show], path: "results", as: 'results'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/survey.rb
class Survey < ApplicationRecord
  belongs_to :user
  has_many :questions, inverse_of: :survey, dependent: :destroy
  has_many :propositions, through: :questions
  has_many :axes, through: :questions

  accepts_nested_attributes_for :questions, reject_if: :all_blank, allow_destroy: true

  validates :title, presence: true, length: { minimum: 3 }, uniqueness: { scope: :user }
  validates :description, presence: true, length: { minimum: 10 }
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  def index
    @surveys = policy_scope(Survey).order(created_at: :desc)
    authorize @surveys
  end

  def new
    @survey = Survey.new
    @question = @survey.questions.build
    @proposition = @question.propositions.build
    authorize @survey
  end

  def create
    if params[:survey_id]
      duplicate
    else
      @survey = Survey.new(surveys_params)
      @survey.user = current_user
      authorize @survey
      @survey.save ? (redirect_to surveys_path) : (render :new)
    end
  end

  def show
    @questions = @survey.questions
    if (params[:next_question])
      @next_question = Question.find(params[:next_question].to_i)
    else
      @next_question = @questions.first
    end
    @question = Question.new
    @group_campaign = GroupCampaign.where(campaign: @current_campaign, group: @current_group).first
  end

  def edit
  end

  def update
    @survey.update(surveys_params)
    if @survey.save
      redirect_to surveys_path
    else
      render :edit
    end
  end

  def destroy
    @survey.destroy
    redirect_to surveys_path
  end

  private

  def duplicate
    survey = Survey.find(params[:survey_id])
    authorize survey
    title = get_next_free_title(survey)
    dup_survey = Survey.new(title: title, description: survey.description, user: current_user)
    dup_survey.save
    survey.questions.each { |question| duplicate_question(question, dup_survey) }
    redirect_to surveys_path
  end

  def get_next_free_title(survey)
    i = 1
    until title_free?("#{survey.title} (copie #{i})")
      i += 1
    end
    "#{survey.title} (copie #{i})"
  end

  def title_free?(title)
    Survey.where(title: title).empty?
  end

  def set_survey
    @survey = Survey.find(params[:id])
    authorize @survey
  end

  def surveys_params
    params.require(:survey).permit(:title, :description,
                                   questions_attributes: [:id, :title, :axe_id, :coef, :_destroy,
                                                          propositions_attributes: [:id, :title, :value, :_destroy]])
  end

  def duplicate_question(question, new_survey)
    dup_question = Question.new(title: question.title, coef: question.coef, axe: question.axe, survey: new_survey)
    dup_question.save
    question.propositions.each { |proposition| duplicate_proposition(proposition, dup_question) }
  end

  def duplicate_proposition(proposition, new_question)
    dup_proposition = Proposition.new(title: proposition.title, value: proposition.value, question: new_question)
    dup_proposition.save
  end
end

app/views/surveys/_form.html.erb
<%= simple_form_for @survey do |f| %>
  <div class="twi-form survey-form-element">
    <%= f.input :title, placeholder: 'Titre', label: false %>
    <%= f.input :description, placeholder: 'Description du questionnaire', label: false %>
  </div>
  <h5>Questions</h5>
  <div id="questions">
    <%= f.simple_fields_for :questions do |question| %>
      <%= render 'question_fields', :f => question %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association '<p><i class="fas fa-plus-circle"></i></p>'.html_safe, f, :questions, class: 'add-delete-survey add-element' %>
    </div>
  </div>
  <%= f.submit 'Enregistrer le questionnaire', class: "survey-form-btn twi-btn" %>
<% end %>

app/views/surveys/_proposition_fields.html.erb
<div class="nested-fields twi-form survey-form-element prop-section">
  <%= link_to_remove_association '<i class="fas fa-times"></i>'.html_safe, f, class: 'delete-element add-delete-survey' %>
  <%= f.input :title, placeholder: 'Enoncé de la réponse', label: false %>
  <%= f.input :value, placeholder: 'Valeur de la réponse (0, 1, 2, 3 ...)', label: false %>
</div>

app/views/surveys/_question_card.html.erb
<% answer = question.answers.includes(:proposition).where(user: current_user, group_campaign: @group_campaign, propositions: {question: question}) %>
<% @answer = answer.empty? ? Answer.new : answer.first %>

<div class="question-card" id=<%= "question-#{question.id}" %> >
  <%= simple_form_for @answer, remote: true do |f| %>
    <h5><%= question.title %></h5>
    <div class="radio-btn">
      <%= f.input :proposition_id,
                 as: :radio_buttons,
                 collection: question.propositions,
                 label: '' %>
      <%= f.input :question_id, as: :hidden, input_html: { value: question.id } %>
    </div>
    <% if @current_campaign && policy(Answer).create? %>
      <%= f.submit "Valider", class: 'twi-btn lblue-btn submit-btn'%>
    <% else %>
      <%= f.submit "Valider", disabled: true%>
    <% end %>
  <% end %>
</div>

app/views/surveys/_question_fields.html.erb
<div class="nested-fields twi-form survey-form-element">
  <%= link_to_remove_association '<i class="fas fa-times"></i>'.html_safe, f, class: 'delete-element add-delete-survey' %>
  <%= f.input :title, placeholder: 'Enoncé de la question', label: false %>
  <%= f.association :axe, collection: Axe.where(user: current_user), prompt: "Quel axe concerne cette question ?", label: false %>
  <%= f.input :coef, placeholder: "Coefficient de la question pour l'axe selectionné (1, 2, 3 ...)", label: false %>
  <h6>Propositions</h6>
  <div id="propositions" class="create-survey-grid">
    <%= f.simple_fields_for :propositions do |prop| %>
      <%= render 'proposition_fields', :f => prop %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association '<i class="fas fa-plus-circle"></i>'.html_safe, f, :propositions, class: 'add-delete-survey add-prop' %>
    </div>
  </div>
</div>

app/views/surveys/_survey_card.html.erb
<div class="main-card small-card title-card">
  <div class="info">
    <div class="head">
      <h2><%= survey.title %></h2>
    </div>
  </div>
</div>

app/views/surveys/_survey_card_linked.html.erb
<div class="main-card small-card">
  <%= link_to survey_path(survey), class: 'card-link' do %>
    <div class="info">
      <div class="survey-head">
        <div class="head">
          <h2><%= survey.title %></h2>
        </div>
      </div>
      <p><%= survey.description %></p>
    </div>
  <% end %>
  <div class="right">
    <div class="actions">
      <% if policy(survey).edit? %>
        <%= link_to '<i class="fas fa-pencil-alt"></i>'.html_safe, edit_survey_path(survey) %>
      <% end %>
      <% if policy(survey).destroy? %>
        <%= link_to '<i class="fas fa-trash"></i>'.html_safe, survey_path(survey), method: :delete, data: { confirm: "Etes vous sur de vouloir supprimer le questionnaire #{survey.title} ?" } %>
      <% end %>
      <% if policy(survey).duplicate? %>
        <%= link_to '<i class="fas fa-clone"></i>'.html_safe, surveys_path(survey_id: survey.id), method: :post %>
      <% end %>
    </div>
  </div>
</div>

app/views/surveys/edit.html.erb
<h1>Edit survey</h1>
<%= render "form" %>

app/views/surveys/index.html.erb
<div class="new-survey-action">
  <% if policy(Survey).create? %>
    <%= link_to 'Créer un nouveau questionnaire', new_survey_path, class: "twi-btn lblue-btn" %>
  <% end %>
</div>

<div class="survey-cards index-survey-cards">
  <% @surveys.each do |survey| %>
    <%= render 'survey_card_linked', survey: survey %>
  <% end %>
</div>

app/views/surveys/new.html.erb
<h1>Nouveau questionnaire</h1>
<div class='survey-form-container'>
  <%= render "form" %>
</div>

app/views/surveys/show.html.erb
<div class="survey-cards">
  <%= render 'survey_card', survey: @survey %>
</div>

<div data-controller='survey-navigation'>
  <div class="question-container">
    <div class="questions-flow">
    <div class="line"></div>
    <% @questions.each do |question| %>
      <div class="question-access <% if question.answered?(current_user) %> answered <% end %>
                  <% if question == @next_question %>
                    active
                  <% end %>"
           data-question='question-<%= question.id %>'
           data-action="click->survey-navigation#navigate"
      >
        <%= question.axe.icon.html_safe %>
      </div>
    <% end %>
    </div>

    <div class="question-cards">
      <% @questions.each do |question| %>
        <div class='question-<%= question.id %>
                    <% unless question === @next_question %>
                      hidden-question
                    <% end %>'
        >
          <%= render 'question_card', question: question, current_campaign: @current_campaign %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="navigation-buttons">
    <% prev_class = @next_question == @questions.first ? 'lblue-btn twi-btn back hidden-button' : 'lblue-btn twi-btn back'%>
    <% next_class = @next_question == @questions.last ? 'lblue-btn twi-btn next hidden-button' : 'lblue-btn twi-btn next'%>
    <%= link_to 'Précédente', "#", class: prev_class, 'data-action': "click->survey-navigation#previous"%>
    <%= link_to 'Passer', "#", class: next_class, 'data-action': "click->survey-navigation#next"%>
  </div>
</div>